# This is a basic workflow to help you get started with Actions

name: BuildCheck

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: 
      - main
      - develop
      - feature/*
      - bugfix/*
  pull_request:
    branches: 
      - main 

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    container: 
      image: palexander23/rp2040-docker:v1.0.0
      options: --user root

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Install Packages
        run: |
            apt-get install -y git

      - uses: actions/checkout@v3
      
      - name: Check Formatting 
        run: |
           ./checkformat.sh

      - name: Check Documentation
        run: ./generate-docs.sh

      - name: Initialize Submodules
        run: |
          git submodule update --init --jobs 9
          cd pico-sdk && git submodule update --init --jobs 9 

      - name: Configure CMake Build
        run: ./configure.sh

      - name: Run Build 
        run: ./build.sh 

      - name: Run Unit Tests
        run : ./run-tests.sh
